//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBroker.Models.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectBrokerEntities : DbContext
    {
        public ProjectBrokerEntities()
            : base("name=ProjectBrokerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d_department> d_department { get; set; }
        public virtual DbSet<p_person> p_person { get; set; }
        public virtual DbSet<phs_projhostingenv> phs_projhostingenv { get; set; }
        public virtual DbSet<pms_projmanagementenv> pms_projmanagementenv { get; set; }
        public virtual DbSet<pr_project> pr_project { get; set; }
        public virtual DbSet<s_student> s_student { get; set; }
        public virtual DbSet<t_teacher> t_teacher { get; set; }
        public virtual DbSet<tm_team> tm_team { get; set; }
    }
}
