//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBroker.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class lpr_login_person_relation
    {
        public int lpr_l_login { get; set; }
        public string lpr_p_person { get; set; }
        public string lpr_username { get; set; }
    
        public virtual l_login_info l_login_info { get; set; }
        public virtual p_person p_person { get; set; }
    }
}
