//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBroker.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_person
    {
        public string p_id { get; set; }
        public string p_fname { get; set; }
        public string p_lname { get; set; }
        public string p_email { get; set; }
        public string p_password { get; set; }
    
        public virtual s_student s_student { get; set; }
        public virtual t_teacher t_teacher { get; set; }
    }
}
