//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBroker.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_person()
        {
            this.lpr_login_person_relation = new HashSet<lpr_login_person_relation>();
        }
    
        public string p_id { get; set; }
        public string p_fname { get; set; }
        public string p_lname { get; set; }
        public string p_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lpr_login_person_relation> lpr_login_person_relation { get; set; }
        public virtual s_student s_student { get; set; }
        public virtual t_teacher t_teacher { get; set; }
    }
}
