//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBroker.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_student()
        {
            this.tm_team = new HashSet<tm_team>();
        }
    
        public string s_nr { get; set; }
        public string s_address { get; set; }
        public System.DateTime s_dob { get; set; }
        public string s_phonenr { get; set; }
        public string s_d_department { get; set; }
    
        public virtual d_department d_department { get; set; }
        public virtual p_person p_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_team> tm_team { get; set; }
    }
}
